package:
  name: sourcetracker2
  version: "2.0.1"

#source:
#  git_url: https://github.com/biota/sourcetracker2.git

build:
  number: 3

requirements:
  build:
    - python
    - pip
    - nose
    - pep8
    - flake8
    - IPython>4.0.0
    - notebook
    - scikit-bio
    - biom-format
    - numpy
    - scipy
    - matplotlib
    - pandas
    - seaborn

  run:
    - python
    - pip
    - nose
    - pep8
    - flake8
    - IPython>4.0.0
    - notebook
    - scikit-bio
    - biom-format
    - numpy
    - scipy
    - matplotlib
    - pandas
    - seaborn

test:
  files:
    - test_counts.biom
    - test_meta_1.tsv
  commands:
    - sourcetracker2 gibbs --help
    - sourcetracker2 --table_fp test_counts.biom --mapping_fp test_meta_1.tsv --output_dir ./test_results --jobs 7 --source_rarefaction_depth 0 --sink_rarefaction_depth 0 --burnin 2
    - test `cat test_results/mixing_proportions.txt | tr "\t" "\n" | wc -l` -eq 42

about:
  home: https://github.com/biota/sourcetracker2
  summary: 'SourceTracker is designed to predict the source of microbial communities in a set of input samples (i.e., the sink samples)'
  description: |
