package:
  name: isolateasvs
  version: "0.1.0"

build:
  number: 1

requirements:
  run:
    - blast
    - cd-hit
    - mafft

test:
  commands:
    - blastn -help
    - mafft --version

about:
  summary: 'BLAST cd-hit and mafft to find ASV to longer isolate DNA associations'
